services:
  # --- 1. Database untuk Odoo (PostgreSQL) ---
  db:
    image: postgres:15
    container_name: odoo_db_17
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
    volumes:
      - odoo-db-data:/var/lib/postgresql/data
    restart: always
    ports:
      - "5434:5432" # Akses dari DBeaver via port 5434

  # --- 2. Odoo 17 Enterprise + Custom ---
  odoo:
    build: .  
    container_name: odoo_app_17
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      # ... volumes tetap sama ...
      - odoo-web-data:/var/lib/odoo
      - ./config/odoo.conf:/etc/odoo/odoo.conf
      - /Users/mac/PycharmProjects/alamui/enterprise17:/mnt/enterprise-addons
      - /Users/mac/PycharmProjects/alamui/alamui_addons:/mnt/extra-addons
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
    restart: always

  # --- 3. Web Server (PHP 8.2 + Apache) ---
  php-web:
    image: php:8.2-apache
    container_name: php_web_dev
    ports:
      - "8080:80"
    volumes:
      - ./web-project:/var/www/html
    restart: always

# Volume persisten
volumes:
  odoo-web-data:
  odoo-db-data: